config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts
  post 'comments/create' => 'posts#comment_create' ,as: :comment_create
  get 'comments/edit' => 'posts#comment_edit' , as: :comment_edit
  patch 'comments/update' => 'posts#comment_update', as: :comment_update
  delete 'comments/delete/:id' => 'posts#comment_destroy', as: :comment_delete
  post 'images/edit/:id' => 'posts#image_edit', as: :image_edit

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post 
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image , styles: {medium: "300x300>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	has_many :comments , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to root_path
		else
			render "new"
		end
	end
	def edit
		@post = Post.find(params[:id])
	end
	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			redirect_to posts_path
		else
			render "edit"
		end

	end
	def show
		@post = Post.find(params[:id])
		@comment = Comment.new(post_id: @post.id)
	end
	def destroy
		@post = Post.find(params[:id])
		if !@post.destroy.blank?
			flash[:message] = "delete succesfull"
			redirect_to root_path
		else
			flash[:message] = "oops something went wrong"
			redirect_to root_path
		end
	end

	def comment_create
		@comment = Comment.new
		@comment.body = params[:comment][:body]
		@comment.post_id = params[:post_id]
		@comment.save
		respond_to do |format|
		  format.js
		  format.html
		end
	end

	def comment_edit
		@comment = Comment.find(params[:comment_id])
		respond_to do |format|
			format.js
			format.html
		end
	end

	def comment_update
		@comment = Comment.find(params[:comment_id])
		@comment.body = params[:comment][:body]
		if @comment.save
			redirect_to post_path(@comment.post_id)
		else
			render 'comment_edit'
		end
	end
	
	def comment_destroy
		@comment = Comment.find(params[:id])
		post_id = @comment.post_id
		if @comment.destroy
			redirect_to post_path(post_id)
		else
			render 'show'
		end

	end

	def image_edit
		@post = Post.find(params[:id])
		respond_to do |format|
		  format.js
		  format.html
		end
	end
	private

		def post_params
			params.require(:post).permit(:title , :body , :image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<embed src="mammoth.mp3" autostart="true" loop="true" hidden="true"><embed>

<% if !flash[:message].blank? %>
	<div class="container">
		<%= flash[:message]%>
	</div>
<% end %>
<%= yield %>

</body>
</html>

app/views/posts/_comment_edit.html.slim
= simple_form_for @comment , url: comment_update_path(comment_id: @comment.id) , :html => { :class => 'form-inline' } do |f|
					= f.input_field :body , placeholder: "enter a comment..."
					=f.submit 'post' , class: "btn btn-success"

app/views/posts/comment_create.js.erb
location.reload();

app/views/posts/comment_edit.html.slim
= render 'comment_edit'

app/views/posts/comment_edit.js.erb
$(".a-unique-class").html('<%= j render "posts/comment_edit" %>');
$(".a-unique-class").modal('show');

app/views/posts/edit.html.slim
.container
	.row.well
		= simple_form_for @post do |f|
		  =f.input :title
		  br
		  =f.input :body
		  br
		  .row 
		  	.col-md-6
		  		= image_tag @post.image.url 
		  		br
		  		.btn.btn-primary.show-edit-image
		  					| Change
		  	.col-md-6
		  		.text-center.edit-image.hide
		  			| hola mes amigos here is where the delete button will be
		  			/ = simple_form_for @post, url: image_edit_path(id: @post.id) , html: {multipart: true} , method: :post , remote: :true do |f|
		  			= f.input :image
		  				/ = f.submit 'change' , class: "btn btn-warning"
		  .text-center
		  	=f.submit 'save' , class: "btn btn-success"
	.container
		.well
			.page-reload.btn.btn-success
				| reload the goddamm page
				

app/views/posts/index.html.slim
| this is the index page
br
| total number of posts
= @posts.count
.container
	- @posts.each do |post|
		.well
			.text-center.post-title
				= post.title
				br
				= post.id
			.text-center.post-body
				= post.body
			.row
				.container
					.text-center
						= link_to 'view', post_path(post.id), class: "btn bn-default"
.container
	.row
		.col-sm-4
			= link_to 'new_post', new_post_path, class: "btn btn-primary"

app/views/posts/new.html.slim
.container
	.row.well
		= simple_form_for @post do |f|
		  =f.input :title
		  br
		  =f.input :body
		  br
		  = f.input :image
		  br
		  .text-center
		  	=f.submit 'save' , class: "btn btn-success"

app/views/posts/show.html.slim
.container
	.well 
		h1.text-center
			= @post.title
			= @post.comments.count
		br
		h5.text-body
			= @post.body
		br
			= image_tag @post.image.url
		.row
			.col-sm-6
				.text-center
					= link_to 'edit', edit_post_path(id: @post.id) , class: "btn btn-info"
			.col-sm-6
				.text-center
					= link_to 'delete', @post , method: :delete , class: "btn btn-warning"	
		.row
			| check
			- a = root_path
			= link_to "home" , root_path, class: "btn btn-default"
	
	- if @post.comments.count != 0
		 - @post.comments.all.each do  |comment|
			.container
				.text-center
					.row				
					 	= comment.body
					 	/ = link_to 'edit' ,comment_edit_path(comment_id: comment.id),remote: :true, "data-toggle" => "modal", "data-target" => "#my-modal" 
					 	= link_to 'edit' ,comment_edit_path(comment_id: comment.id) 
					 	= link_to 'delete', comment_delete_path(id: comment.id) , method: :delete , class: "btn btn-warning"
					.clearfix	
					 	#my-modal.modal  title=("My modal")
							/ .modal-dialog 	
							/  	.modal-content
							 		.modal-body.a-unique-class
							 		/ 	/ = render "comment_edit"
							 		/ 	= simple_form_for @comment , url: root_path, remote: :true , :html => { :class => 'form-inline' } do |f|
										/ 	= f.input_field :body , placeholder: "enter a comment..."
										/ 	=f.submit 'post' , class: "btn btn-success"
							 		/ button.btn aria-hidden="true" data-dismiss="modal"  Close

				 		br
	.container
		.text-center
			= simple_form_for @comment , url: comment_create_path(post_id: @post.id) , remote: :true , :html => { :class => 'form-inline' } do |f|
					= f.input_field :body , placeholder: "enter a comment..."
					=f.submit 'post' , class: "btn btn-success"
	br
	.container
		.text-center
			- a = root_path
				= link_to "home" , a , class: "btn btn-default"
br
br
.container
	.text-center
		button.btn.btn-lg data-target="#my-modal" data-toggle="modal"  Open a modal
		#my-modal.modal.fade
			.modal-dialog
				.modal-content
					.modal-body
						| Bull shit text
					.modal-footer
						button.btn data-dismiss="modal" close